### ISSUE TITLE
Hornet Fountain Incorrect Logic?

### ISSUE THREAD

**Issue by TheMysticalBard** [Korzer420/LoreRandomizer#5]
Just started playing rando again and I quickly got softlocked. It appears the reason for the softlock was that the hornet fountain talk was in logic despite me never encountering hornet (I had nothing to kill baldurs with, couldn't even get in to greenpath). Let me know if you need any additional files to debug, I'm not sure what to provide here.

**Comment by Korzer420** [comment]
Hey, the logic does seem fine to me. Which type of traveller order did you choose? In any case, could you provide me:

- The modlog of that play session
- The userX.modded.json file in the same directory (X = Save Slot number)
- The whole folder under Randomizer 4 from the seed you played.

**Comment by TheMysticalBard** [comment]
Traveller order was set to Vanilla. I do have quite a few connections (as you will see in the files) and the issue may have been caused by an incompatibility somewhere. Unfortunately I was a bit stupid and saved over the old save with a new one, so I don't think the save will be useful, in fact none of it may be (but I have included the latest save backup instead of the save, just in case it's from the old run).

[This is the randomizer 4 folder for the new run, settings were MOSTLY the same but I did change more doors to use all the doors instead of some doors.](https://github.com/Korzer420/LoreRandomizer/files/14606779/Randomizer4_user7_NEW.zip)

[This is the latest backup of the modded json, may be from the new run.](https://github.com/Korzer420/LoreRandomizer/files/14606795/user7_bak.modded.json)

[This is the only old modlog with any randomization attempts. The current one may also be useful (has both old run play and new run play).](https://github.com/Korzer420/LoreRandomizer/files/14606821/ModLog.03.10.2024.20.14.49.txt)

[This is the modlog from when I deleted the old run and made the new run. It has some play of the old run in there, unsure if it will be useful or not.](https://github.com/Korzer420/LoreRandomizer/files/14606896/ModLog.txt)

Apologies for losing most of the evidence, I am quite frustrated with myself. Hopefully this gives some info for you. Let me know if there's anything else I can do. Thanks!

**Comment by TheMysticalBard** [comment]
I'm pretty sure the incompatibility is with darkness randomizer. NPCs can be talked to in darkness when it thinks they can't. Additionally, there's no logic for eg. Hornet Greenpath when the room is totally dark. Not too sure what to do about it.

**Comment by Korzer420** [comment]
Sorry for the late response.

Without the actual files it is hard to determine how this issue came to be.

Let me clarify this.

The logic assumed you can talk to Hornet at the fountain. Presumably because you already picked up a Hornet level before, as encountering her there doesn't have to be in sequence if the level has been obtained prior. Basically like this: If you don't have a Hornet level, she only appears in Greenpath. If you have 1, she can be encountered in Greenpath AND the fountain (assuming you haven't already picked the item up).

Did she not appear at the fountain despite having a Hornet level already or didn't you obtain a level for her to appear in the first place?

Regarding the other connections. Darkness Rando may in fact cause issues with the locations which I will address with the dev of it. Breakable Wall Rando is known for having some issues, but the dev isn't active anymore. Considering other connection devs also ignore BWR cause of this fact. I'll do the same.

**Comment by Korzer420** [comment]
The Hornet Fountain wasn't working due to a bug in KorzUtils. It should work now
